/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;
import java.time.format.DateTimeParseException; // para a Exception o para o erro no cadastro quando entrada e saida vazios
import com.sun.glass.events.KeyEvent;
import negocio.Veiculo; 
import persistencia.ControlaVeiculo;
import java.time.LocalTime;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author S.I
 */
public class Cadastro extends javax.swing.JInternalFrame {

    ControlaVeiculo cv = new ControlaVeiculo(); //
    
    public Cadastro() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVeiculo = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField() {
            @Override
            protected javax.swing.text.Document createDefaultModel() {
                return new javax.swing.text.PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, javax.swing.text.AttributeSet a) throws javax.swing.text.BadLocationException {
                        super.insertString(offs, str.toUpperCase(), a);
                    }
                };
            }
        };
        txtSaida = new javax.swing.JFormattedTextField();
        txtEntrada = new javax.swing.JFormattedTextField();
        bntCadastrar = new javax.swing.JButton();
        lblPlaca1 = new javax.swing.JLabel();
        cbVeiculo = new javax.swing.JComboBox<>();
        lblVaga = new javax.swing.JLabel();
        txtVaga = new javax.swing.JTextField() {
            @Override
            protected javax.swing.text.Document createDefaultModel() {
                return new javax.swing.text.PlainDocument() {
                    @Override
                    public void insertString(int offs, String str, javax.swing.text.AttributeSet a) throws javax.swing.text.BadLocationException {
                        super.insertString(offs, str.toUpperCase(), a);
                    }
                };
            }
        };
        ;
        bntVerTodos = new javax.swing.JButton();

        setTitle("Cadastro de Veículo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVeiculo.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 24)); // NOI18N
        lblVeiculo.setText("VEICULO:");
        jPanel1.add(lblVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, 26));

        lblEntrada.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 24)); // NOI18N
        lblEntrada.setText("ENTRADA:");
        jPanel1.add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 105, 26));

        lblSaida.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 24)); // NOI18N
        lblSaida.setText("SAIDA:");
        jPanel1.add(lblSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 92, 26));

        txtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlacaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 148, -1));

        try {
            txtSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaidaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 149, -1));

        try {
            txtEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntradaKeyPressed(evt);
            }
        });
        jPanel1.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 149, -1));

        bntCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/caixa-de-entrada.png"))); // NOI18N
        bntCadastrar.setText("CADASTRAR");
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bntCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        lblPlaca1.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 24)); // NOI18N
        lblPlaca1.setText("PLACA:");
        jPanel1.add(lblPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 92, 26));

        cbVeiculo.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 18)); // NOI18N
        cbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRO", "MOTO" }));
        jPanel1.add(cbVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 148, -1));

        lblVaga.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 24)); // NOI18N
        lblVaga.setText("VAGA:");
        jPanel1.add(lblVaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 26));

        txtVaga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVagaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVagaKeyTyped(evt);
            }
        });
        jPanel1.add(txtVaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 148, -1));

        bntVerTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/relatorio.png"))); // NOI18N
        bntVerTodos.setText("RELATÓRIO");
        bntVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVerTodosActionPerformed(evt);
            }
        });
        jPanel1.add(bntVerTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
     //LIMITE DE CARACTERES ACEITOS:   
    int maxCharacters = 7; // Define o número máximo de caracteres permitidos
    if (txtPlaca.getText().length() >= maxCharacters) {
        evt.consume(); // Impede que o caractere seja inserido
    }
    
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void txtPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyPressed
    
        // clicar enter e passar para proximo campo
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtEntrada.requestFocus();            //informação de qual campo ele vai parar quando clicar no enter
        }
    }//GEN-LAST:event_txtPlacaKeyPressed

    private void txtEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyPressed
        // TODO add your handling code here:
        // clicar enter e passar para proximo campo
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtSaida.requestFocus();            //informação de qual campo ele vai parar quando clicar no enter
        }
    }//GEN-LAST:event_txtEntradaKeyPressed

    private void txtSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaidaKeyPressed
        // TODO add your handling code here:
        // clicar enter e passar para proximo campo
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            bntCadastrar.requestFocus();            //informação de qual campo ele vai parar quando clicar no enter
        }
    }//GEN-LAST:event_txtSaidaKeyPressed

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        
        Veiculo veiculo = new Veiculo();
        
        //VERIFICAR se todos os CAMPOS estão PREENCHIDOS
        if (txtVaga.getText().isEmpty() || txtPlaca.getText().isEmpty() || txtEntrada.getValue() == null || 
            txtSaida.getValue() == null) { JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.", 
            "Aviso", JOptionPane.WARNING_MESSAGE);
    } else {
            try {
        LocalTime entrada = LocalTime.parse(txtEntrada.getText());
        LocalTime saida = LocalTime.parse(txtSaida.getText());
        
        // Resto do código para o cadastro
        
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Formato inválido para a hora.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
            
        // Lógica para realizar o cadastro
        
        veiculo.setPlaca(txtPlaca.getText());
        //CODIGO DE TESTE:
        veiculo.setVaga(txtVaga.getText());
        veiculo.setTipo((String)cbVeiculo.getSelectedItem());
        
        //codigo NOVO calculo de horas
        
        Object entradaValue = txtEntrada.getValue();
        Object saidaValue = txtSaida.getValue();

if (entradaValue != null && saidaValue != null) {
    String entradaStr = entradaValue.toString();
    String saidaStr = saidaValue.toString();

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
    LocalTime entrada = LocalTime.parse(entradaStr, formatter);
    LocalTime saida = LocalTime.parse(saidaStr, formatter);
    
 Duration duracao;
if (saida.isBefore(entrada)) {
    // Ajusta a saída para considerar a passagem da meia-noite
    duracao = Duration.between(entrada, LocalTime.MAX).plus(Duration.between(LocalTime.MIN, saida));
} else {
    duracao = Duration.between(entrada, saida);
}

long horasEstacionado = duracao.toMinutes();
veiculo.setHorasEstacionado(horasEstacionado);

// para ver se enviar a hora de entrada e saida para o jtable

         veiculo.setEntrada(entrada);
         veiculo.setSaida(saida);
        
}
        
        //-------------------------
        if(cv.salvar(veiculo)){
            JOptionPane.showMessageDialog(null,"Veiculo cadastrado com sucesso.");
            txtPlaca.setText("");
            txtVaga.setText("");
            //novo
            txtEntrada.setValue("");
            txtSaida.setValue("");
            txtVaga.requestFocus();      
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar veículo.");
        }      
    }
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void bntVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVerTodosActionPerformed
        // TODO add your handling code here:
        DlgMostraVeiculos dlg = new DlgMostraVeiculos(null, true, cv);
        dlg.setVisible(true);
        
    }//GEN-LAST:event_bntVerTodosActionPerformed

    private void txtVagaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVagaKeyTyped
     
        int maxCharacters = 3; // Define o número máximo de caracteres permitidos

        if ( txtVaga.getText().length() >= maxCharacters) {
        evt.consume(); // Impede que o caractere seja inserido
    }

    }//GEN-LAST:event_txtVagaKeyTyped

    private void txtVagaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVagaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtPlaca.requestFocus();            //informação de qual campo ele vai parar quando clicar no enter
        }
    }//GEN-LAST:event_txtVagaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton bntVerTodos;
    private javax.swing.JComboBox<String> cbVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblVaga;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JFormattedTextField txtEntrada;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JFormattedTextField txtSaida;
    private javax.swing.JTextField txtVaga;
    // End of variables declaration//GEN-END:variables
}
